services:
  etl:
    image: python:3.13.3-alpine
    working_dir: /app
    volumes:
      - ./etl.py:/app/etl.py
      - ./concert_tours_by_women.csv:/app/concert_tours_by_women.csv
      - ./requirements_etl.txt:/app/requirements.txt
      - ./volume:/app/volume
    command: >
      sh -c "
      pip install --no-cache-dir -r requirements.txt;
      mkdir -p /app/volume;
      python3 etl.py
      "

  job:
    image: python:3.13.3-alpine
    working_dir: /app
    depends_on:
      etl:
        condition: service_completed_successfully
    volumes:
      - ./job.py:/app/job.py
      - ./requirements_job.txt:/app/requirements.txt
      - ./volume:/app/volume
    command: >
      sh -c "
      pip install --no-cache-dir -r requirements.txt;
      mkdir -p /app/volume;
      python3 job.py
      "
volumes:
  volume: